Repository NateRolo/2510_project, pull requests merged in 2025-02, with the labels that each got.

#1 Menu updates
  .idea/2510_project.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/editor.xml
  .idea/modules.xml
  .idea/vcs.xml
  CMakeLists.txt
  cmake-build-debug/.cmake/api/v1/reply/cmakeFiles-v1-70786b4b89ceefc53b2f.json
  cmake-build-debug/.cmake/api/v1/reply/cmakeFiles-v1-aea1bed8a67ff44a1f93.json
  cmake-build-debug/.cmake/api/v1/reply/codemodel-v2-8c705bf522a96c802da5.json
  cmake-build-debug/.cmake/api/v1/reply/index-2025-02-06T22-09-10-0752.json
  cmake-build-debug/.cmake/api/v1/reply/target-2510_project-Debug-acfe872313f0f815881a.json
  cmake-build-debug/.ninja_deps
  cmake-build-debug/.ninja_log
  cmake-build-debug/2510_project.exe
  cmake-build-debug/CMakeFiles/2510_project.dir/main.c.obj
  cmake-build-debug/CMakeFiles/3.30.5/CMakeDetermineCompilerABI_C.bin
  cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/a.exe
  cmake-build-debug/CMakeFiles/CMakeConfigureLog.yaml
  cmake-build-debug/CMakeFiles/clion-Debug-log.txt
  cmake-build-debug/Testing/Temporary/LastTest.log
  cmake-build-debug/build.ninja
  main.c
  main.exe
  patient.h
Labels: enhancement, question

#2 Add new patient update
  main.c
Labels: enhancement

#3 Discharge patient
  main.c
  main.exe
Labels: enhancement

#4 Main refactor
  .vscode/settings.json
  main.c
  main.exe
  patient.c
  patient.h
  utils.c
  utils.h
Labels: documentation, enhancement

#6 refactor: reassign them to static constexpr in c files
  doctor.c
  doctor.h
  patient.c
  patient.h
Labels: enhancement
